apiVersion: skaffold/v1beta2
kind: Config
build:
  artifacts:
  - image: changeme
    context: .
    docker: {}
  tagPolicy:
    envTemplate:
      template: '{{.DOCKER_REGISTRY}}/puja255/ec2-user:{{.VERSION}}'
  local: {}
deploy:
  kubectl: {}
profiles:
- name: dev
  build:
    artifacts:
    - docker: {}
    tagPolicy:
      envTemplate:
        template: '{{.DOCKER_REGISTRY}}/puja255/ec2-user:{{.DIGEST_HEX}}'
    local: {}
  deploy:
    helm:
      releases:
      - name: ec2-user
        chartPath: charts/ec2-user
        setValueTemplates:
          image.repository: '{{.DOCKER_REGISTRY}}/puja255/ec2-user'
          image.tag: '{{.DIGEST_HEX}}'
